name: Promote ReleaseCandidate
description: Promote a release candidate
inputs:
  k8s_repo:
    description: repo of the k8s config
    required: true
  API_GITHUB_TOKEN:
    description: Github token for the k8s repo
    required: true
  PROD_RELEASE_FILE:
    description: path of the release file to update the version
    required: true
  GITHUB_TOKEN:
    description: repo github token
    required: true
runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - name: Set Version
      shell: bash
      run: |
        dotnet-gitversion -output buildserver -verbosity Quiet
        echo "Verison:"
        cat $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.k8s_repo }}
        path: k8s
        token: ${{ inputs.API_GITHUB_TOKEN }}

    - name: Commit Version and create Pullrequest (Flux)
      working-directory: k8s
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.API_GITHUB_TOKEN }}
        RELEASE_FILE: ${{ inputs.PROD_RELEASE_FILE }}
      run: |
        git config user.email deployment@tqgg.de
        git config user.name deployment-bot
        git checkout -b release/$GitVersion_MajorMinorPatch
        sed -i "s/\(.*\):.*#\[version\]/\1: $GitVersion_MajorMinorPatch #[version]/" $RELEASE_FILE
        git add .
        git commit -m "Release: $GitVersion_MajorMinorPatch"
        git push --set-upstream origin release/$GitVersion_MajorMinorPatch
        gh pr create --title "[Release] Deployment: $GitVersion_MajorMinorPatch" --body "[Release] Deployment: $GitVersion_MajorMinorPatch"

    - name: release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        release_name: ${{ env.GitVersion_MajorMinorPatch }}
        tag_name: ${{ env.GitVersion_MajorMinorPatch }}
        body_path: readme.md
